### ISSUE TITLE
Problem installing vector_engin

### ISSUE THREAD

**Issue by evangeliazve** [kstathou/vector_engine#1]
Hello support,

First of all, thank you for the solutions you propose on NLP.

I am trying to implement the solution you propose for vector based search engin (https://towardsdatascience.com/how-to-build-a-semantic-search-engine-with-transformers-and-faiss-dcbea307a0e8) but I cannot install vector_engin as I receive the following error message : 
CalledProcessError: Command 'pip install vector_engine' returned non-zero exit status 1.

![image](https://user-images.githubusercontent.com/19437590/114011088-1b2d3b00-9865-11eb-8011-20e292bd58fb.png)

Could you please help me overpass that problem ? Or is there any bug that has to be fixed on your side ?

Best Regards,
Evangelia Zve

**Comment by kstathou** [comment]
Hi @evangeliazve, thank you for reading my tutorial. This repository is not in PyPI, that's why you cannot install it with `pip install vector_engine`. 

To run the tutorial, I suggest the following:
- For the first part of the tutorial which produces the index used in the search engine, you can use this [colab notebook](https://colab.research.google.com/drive/11WBCrwNzbNWN7QbMEwzy-8MZROOVQFnZ?usp=sharing). 
- For the second part that deploys the search engine in a streamlit application with docker, [follow the instructions here](https://github.com/kstathou/vector_engine#how-to-deploy-the-streamlit-app-locally-with-docker)

Let me know if you have any other questions.

**Comment by evangeliazve** [comment]
Hi @kstathou, thanks your your advices. I succeeded to run the code and have the results I wanted.

Best Regards,
Evangelia Zve

**Comment by kstathou** [comment]
Amazing! Open another issue if you have any other questions. Closing this one.
